"""
omega.nodes.victoria.decision_trace
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Extended decision trace for every candidate generated by the strategy engine.

Unlike DecisionSnapshot (which mirrors the existing TickerDecision to Postgres
and /tmp/), this module writes richer records for ALL ticker candidates in every
cycle — not just the ones that close trades. The goal is to surface *why* the
system passed on near-threshold opportunities.

Each DecisionTrace record adds on top of TickerDecision:
  - Geometry state at decision time (ricci, orc_mean, geo_dist_crash, fiedler_raw)
  - Exact thresholds applied post-thresh_scale
  - A human-readable explanation string
  - A threshold_gap metric (w_conv - threshold), negative means rejected

Written to: data/decision_traces/{version}.jsonl — one JSON per line.

The Go API reads these for the Decision Replay dashboard view via
GET /api/v1/training/decision-traces?version=vN&limit=N&filter=rejected_close.
"""

from __future__ import annotations

import json
import logging
import math
from collections.abc import Iterator
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger("omega.nodes.victoria.decision_trace")

# How close to the threshold counts as "near" (for filtering in the replay UI).
# A decision with |threshold_gap| < NEAR_THRESHOLD_BAND is "near-threshold".
NEAR_THRESHOLD_BAND = 0.03


# ---------------------------------------------------------------------------
# DecisionTrace — one ticker's full decision record for one cycle
# ---------------------------------------------------------------------------


@dataclass
class DecisionTrace:
    """Extended decision record for one ticker in one cycle.

    Captures everything needed to understand WHY a decision was made or blocked.
    """

    ticker: str
    cycle: int
    version: str
    timestamp: str

    # ── Signal values at decision time ──────────────────────────────────────
    signals: dict[str, float] = field(default_factory=dict)
    """All *_signal values + sma_crossover in [-1, 1]."""

    # ── Composite state ─────────────────────────────────────────────────────
    raw_composite: float = 0.0
    demeaned_composite: float = 0.0
    basket_mean: float = 0.0
    basket_std: float = 0.0
    weighted_conviction: float = 0.0

    # ── Regime state ────────────────────────────────────────────────────────
    regime: str = "unknown"
    bear_prob: float = -1.0
    bull_prob: float = -1.0
    thresh_scale: float = 1.0

    # ── Thresholds applied (after thresh_scale) ──────────────────────────
    long_thresh: float = 0.0
    short_thresh: float = 0.0
    abs_min_conviction: float = 0.06

    # ── Geometry state ──────────────────────────────────────────────────────
    ricci_scalar: float = 0.0
    orc_mean: float = 0.0
    geo_dist_crash: float = float("inf")
    fiedler_raw: float = 1.0

    # ── Filter chain ────────────────────────────────────────────────────────
    proposal: str = "NONE"
    """LONG / SHORT / NONE"""
    filters_fired: list[str] = field(default_factory=list)
    """Ordered list of filter names that evaluated this candidate."""
    blocking_filter: str = ""
    """The specific filter that blocked the trade (empty if passed or HOLD)."""
    final_decision: str = "HOLD"
    """TRADE / FILTERED / HOLD / SIT_OUT"""

    # ── Near-threshold metric ────────────────────────────────────────────────
    threshold_gap: float = 0.0
    """abs(weighted_conviction) - applicable_threshold.
    Negative = rejected (by how much), positive = passed (by how much).
    Useful for finding near-misses that the system almost traded."""

    # ── Human-readable explanation ───────────────────────────────────────────
    explanation: str = ""
    """One-sentence summary of why this decision was made."""

    reasoning: str = ""
    """Structured multi-clause reasoning (signal drivers, regime, gate status, gap).
    Populated when signal_reasoning feature flag is ON. Rendered as tooltip in dashboard."""

    def to_dict(self) -> dict[str, Any]:
        d = asdict(self)
        # Replace inf/nan with None for JSON safety
        for k, v in list(d.items()):
            if isinstance(v, float) and (math.isinf(v) or math.isnan(v)):
                d[k] = None
        return d

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> DecisionTrace:
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})

    @property
    def is_near_threshold(self) -> bool:
        """True if this was a close call — rejected but within NEAR_THRESHOLD_BAND."""
        return (
            self.final_decision == "FILTERED"
            and self.blocking_filter.startswith(("weighted_conviction", "abs_min_conviction"))
            and abs(self.threshold_gap) < NEAR_THRESHOLD_BAND
        )


# ---------------------------------------------------------------------------
# build_explanation — produce a human-readable summary
# ---------------------------------------------------------------------------


def build_explanation(trace: DecisionTrace) -> str:
    """Generate a terse, human-readable explanation of the decision."""
    if trace.final_decision == "HOLD":
        return f"{trace.ticker}: HOLD — composite {trace.demeaned_composite:+.3f} below conviction threshold"

    if trace.final_decision == "TRADE":
        direction = "LONG" if trace.proposal == "LONG" else "SHORT"
        return (
            f"{trace.ticker}: {direction} — w_conv={trace.weighted_conviction:+.3f} "
            f"(thresh={(trace.long_thresh if direction == 'LONG' else trace.short_thresh):.3f}), "
            f"regime={trace.regime}, ricci={trace.ricci_scalar:+.2f}, fiedler={trace.fiedler_raw:.2f}"
        )

    # FILTERED
    if not trace.blocking_filter:
        return f"{trace.ticker}: FILTERED (unknown filter)"

    if trace.blocking_filter.startswith("weighted_conviction"):
        gap = trace.threshold_gap
        thresh = trace.long_thresh if trace.proposal == "LONG" else trace.short_thresh
        return (
            f"{trace.ticker}: {trace.proposal} REJECTED — w_conv={trace.weighted_conviction:+.3f} "
            f"missed threshold {thresh:.3f} by {-gap:.3f} "
            f"({'regime=' + trace.regime + ', '}fiedler={trace.fiedler_raw:.2f})"
        )

    if trace.blocking_filter.startswith("abs_min_conviction"):
        return (
            f"{trace.ticker}: {trace.proposal} REJECTED — abs_min floor "
            f"(w_conv={abs(trace.weighted_conviction):.3f} < {trace.abs_min_conviction:.3f})"
        )

    if trace.blocking_filter == "time_filter":
        return (
            f"{trace.ticker}: {trace.proposal} SKIPPED — time filter (too soon after last trade)"
        )

    if "regime_block" in trace.blocking_filter:
        return (
            f"{trace.ticker}: {trace.proposal} BLOCKED — regime gate "
            f"(bear_prob={trace.bear_prob:.2f}, bull_prob={trace.bull_prob:.2f})"
        )

    return f"{trace.ticker}: {trace.proposal} FILTERED — {trace.blocking_filter}"


# ---------------------------------------------------------------------------
# TraceWriter — appends DecisionTrace records to JSONL
# ---------------------------------------------------------------------------


class TraceWriter:
    """Writes DecisionTrace records to data/decision_traces/{version}.jsonl.

    One JSON object per line. Safe to call every cycle; buffer is flushed per
    write so the file is always readable mid-run.
    """

    def __init__(self, version: str, output_dir: str = "data") -> None:
        self._version = version
        self._dir = Path(output_dir) / "decision_traces"
        self._dir.mkdir(parents=True, exist_ok=True)
        self._path = self._dir / f"{version}.jsonl"
        self._fh = open(self._path, "a")
        logger.info("TraceWriter: writing to %s", self._path)

    @property
    def path(self) -> Path:
        return self._path

    def write(self, trace: DecisionTrace) -> None:
        try:
            self._fh.write(json.dumps(trace.to_dict()) + "\n")
            self._fh.flush()
        except Exception as exc:
            logger.warning("TraceWriter: write failed: %s", exc)

    def write_many(self, traces: list[DecisionTrace]) -> None:
        try:
            for t in traces:
                self._fh.write(json.dumps(t.to_dict()) + "\n")
            self._fh.flush()
        except Exception as exc:
            logger.warning("TraceWriter: batch write failed: %s", exc)

    def close(self) -> None:
        import contextlib

        with contextlib.suppress(Exception):
            self._fh.close()


# ---------------------------------------------------------------------------
# TraceReader — load and filter traces for analysis
# ---------------------------------------------------------------------------


class TraceReader:
    """Reads DecisionTrace records from JSONL for analysis or the dashboard."""

    def __init__(self, path: str | Path) -> None:
        self._path = Path(path)

    def iter_traces(self) -> Iterator[DecisionTrace]:
        """Generator over all traces. Memory-efficient for large files."""
        if not self._path.exists():
            return
        with open(self._path) as f:
            for lineno, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                try:
                    yield DecisionTrace.from_dict(json.loads(line))
                except Exception as exc:
                    logger.warning("TraceReader: line %d error: %s", lineno, exc)

    def near_threshold_rejections(
        self, limit: int = 50, cycle_start: int = 0, cycle_end: int = 999999
    ) -> list[DecisionTrace]:
        """Return up to `limit` near-threshold rejections, sorted by |threshold_gap|."""
        candidates: list[DecisionTrace] = []
        for t in self.iter_traces():
            if cycle_start <= t.cycle <= cycle_end and t.is_near_threshold:
                candidates.append(t)
        candidates.sort(key=lambda x: abs(x.threshold_gap))
        return candidates[:limit]

    def filter_decisions(
        self,
        ticker: str | None = None,
        final_decision: str | None = None,
        cycle_start: int = 0,
        cycle_end: int = 999999,
        limit: int = 200,
    ) -> list[DecisionTrace]:
        """Return filtered traces for exploration."""
        results: list[DecisionTrace] = []
        for t in self.iter_traces():
            if cycle_start <= t.cycle <= cycle_end:
                if ticker and t.ticker != ticker:
                    continue
                if final_decision and t.final_decision != final_decision:
                    continue
                results.append(t)
                if len(results) >= limit:
                    break
        return results
